# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fda1f011a253dc9d72ef629a9b835549faa440337a9f1e58ba9d14d620ed248e7091b18cf68ec65293df15c229ae758e8f6a75c8d5b18cf9b96f159513aa8e77

test:
  secret_key_base: 32a4f7f67522b7f6b497b986c9f594b3e9b387c70d9bbf41ca46fe29ff271023181b80b202c6bed2705105061f3f271ff47b4db58bf90acaa7c81d6610980617

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
